### ISSUE TITLE
span

### ISSUE THREAD

**Issue by mikebutts** [mateufel/prj-rev-bwfs-dasmoto#2]
https://github.com/mateufel/prj-rev-bwfs-dasmoto/blob/82b9cff3756f96d1b9fdba025474f58ae6d1b3ad/DasmotosArtsAndCrafts/index.html#L31-L34

Technically there is nothing wrong with this, but the first span since you are not styling , you don't need the span tags around it.

**Comment by mateufel** [comment]
Thanks for the tip!
